#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fm =						\
	papers/fm/packages.tex					\
	papers/fm/main.tex					\
	papers/fm/01_modulation.tex	\
	papers/fm/01_AM.tex					\
	papers/fm/02_FM.tex			\
	papers/fm/03_bessel.tex					\
	papers/fm/04_fazit.tex					\
	papers/fm/references.bib			

