#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fm =						\
	papers/fm/packages.tex					\
	papers/fm/main.tex					\
	papers/fm/references.bib			

