#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fm =						\
	papers/fm/packages.tex					\
	papers/fm/main.tex					\
	papers/fm/references.bib				\
	papers/fm/teil0.tex					\
	papers/fm/teil1.tex					\
	papers/fm/teil2.tex					\
	papers/fm/teil3.tex

