#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-zeta =						\
	papers/zeta/packages.tex					\
	papers/zeta/main.tex					\
	papers/zeta/references.bib				\
	papers/zeta/einleitung.tex					\
	papers/zeta/analytic_continuation.tex					\
    papers/zeta/zeta_gamma.tex \

