#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-zeta =						\
	papers/zeta/packages.tex					\
	papers/zeta/main.tex					\
	papers/zeta/references.bib				\
	papers/zeta/teil0.tex					\
	papers/zeta/teil1.tex					\
	papers/zeta/teil2.tex					\
	papers/zeta/teil3.tex

