#
# Makefile -- build images for cover
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	spherical30.png spherical31.png spherical32.png spherical33.png

spherical30.png:	common.inc spherical30.pov
	povray +A0.1 +UA +W1080 +H1080 -Ospherical30.png spherical30.pov

spherical31.png:	common.inc spherical31.pov
	povray +A0.1 +UA +W1080 +H1080 -Ospherical31.png spherical31.pov

spherical32.png:	common.inc spherical32.pov
	povray +A0.1 +UA +W1080 +H1080 -Ospherical32.png spherical32.pov

spherical33.png:	common.inc spherical33.pov
	povray +A0.1 +UA +W1080 +H1080 -Ospherical33.png spherical33.pov
