#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/075-fourier/chapter.tex
