#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-lambertw =						\
	papers/lambertw/packages.tex					\
	papers/lambertw/main.tex					\
	papers/lambertw/references.bib				\
	papers/lambertw/teil0.tex					\
	papers/lambertw/teil1.tex					\
	papers/lambertw/teil2.tex					\
	papers/lambertw/teil3.tex

