#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/010-potenzen/loesbarkeit.tex				\
	chapters/010-potenzen/polynome.tex				\
	chapters/010-potenzen/tschebyscheff.tex				\
	chapters/010-potenzen/potenzreihen.tex				\
	chapters/010-potenzen/uebungsaufgaben/101.tex			\
	chapters/010-potenzen/uebungsaufgaben/102.tex			\
	chapters/010-potenzen/uebungsaufgaben/103.tex			\
	chapters/010-potenzen/chapter.tex
