#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/010-potenzen/chapter.tex
