#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/010-potenzen/1-polynome.tex				\
	chapters/010-potenzen/2-loesbarkeit.tex				\
	chapters/010-potenzen/3-tschebyscheff.tex			\
	chapters/010-potenzen/4-rational.tex				\
	chapters/010-potenzen/5-potenzreihen.tex			\
	chapters/010-potenzen/uebungsaufgaben/101.tex			\
	chapters/010-potenzen/uebungsaufgaben/102.tex			\
	chapters/010-potenzen/uebungsaufgaben/103.tex			\
	chapters/010-potenzen/chapter.tex
