#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-integral/1-fehlerfunktion.tex			\
	chapters/060-integral/2-eulertransformation.tex			\
	chapters/060-integral/3-differentialkoerper.tex			\
	chapters/060-integral/31-rational.tex				\
	chapters/060-integral/32-erweiterungen.tex			\
	chapters/060-integral/33-diffke.tex				\
	chapters/060-integral/34-iproblem.tex				\
	chapters/060-integral/35-irat.tex				\
	chapters/060-integral/36-sqratrat.tex				\
	chapters/060-integral/4-risch.tex				\
	chapters/060-integral/41-logexp.tex				\
	chapters/060-integral/42-elementar.tex				\
	chapters/060-integral/43-liouville.tex				\
	chapters/060-integral/chapter.tex
