#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/060-integral/fehlerfunktion.tex			\
	chapters/060-integral/eulertransformation.tex			\
	chapters/060-integral/differentialkoerper.tex			\
	chapters/060-integral/risch.tex					\
	chapters/060-integral/chapter.tex
