#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/075-fourier/1d.tex					\
	chapters/075-fourier/2d.tex					\
	chapters/075-fourier/3-bessel.tex				\
	chapters/075-fourier/chapter.tex
