#
# Makefile.inc -- Makefile dependencies for chapter 11
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/110-elliptisch/ellintegral.tex				\
	chapters/110-elliptisch/jacobi.tex				\
	chapters/110-elliptisch/lemniskate.tex				\
	chapters/110-geometrie/chapter.tex
