#
# Makefile.inc -- Makefile dependencies for chapter 11
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/110-elliptisch/1-ellintegral.tex			\
	chapters/110-elliptisch/2-jacobi.tex				\
	chapters/110-elliptisch/21-elltrigo.tex				\
	chapters/110-elliptisch/22-dglsol.tex				\
	chapters/110-elliptisch/23-mathpendel.tex			\
	chapters/110-elliptisch/3-lemniskate.tex			\
	chapters/110-elliptisch/uebungsaufgaben/1.tex			\
	chapters/110-elliptisch/uebungsaufgaben/2.tex			\
	chapters/110-elliptisch/uebungsaufgaben/3.tex			\
	chapters/110-elliptisch/uebungsaufgaben/4.tex			\
	chapters/110-elliptisch/uebungsaufgaben/5.tex			\
	chapters/110-elliptisch/chapter.tex
