#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fw =						\
	papers/fw/packages.tex					\
	papers/fw/main.tex					\
	papers/fw/references.bib				\
	papers/fw/teil0.tex					\
	papers/fw/teil1.tex					\
	papers/fw/teil2.tex					\
	papers/fw/teil3.tex

