#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/050-differential/1-beispiele.tex			\
	chapters/050-differential/2-potenzreihenmethode.tex		\
	chapters/050-differential/3-bessel.tex				\
	chapters/050-differential/4-hypergeometrisch.tex		\
	chapters/050-differential/uebungsaufgaben/501.tex		\
	chapters/050-differential/uebungsaufgaben/502.tex		\
	chapters/050-differential/uebungsaufgaben/503.tex		\
	chapters/050-differential/uebungsaufgaben/504.tex		\
	chapters/050-differential/chapter.tex
