#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/050-differential/beispiele.tex				\
	chapters/050-differential/potenzreihenmethode.tex		\
	chapters/050-differential/bessel.tex				\
	chapters/050-differential/chapter.tex
