#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/050-differential/beispiele.tex				\
	chapters/050-differential/potenzreihenmethode.tex		\
	chapters/050-differential/bessel.tex				\
	chapters/050-differential/hypergeometrisch.tex			\
	chapters/050-differential/uebungsaufgaben/501.tex		\
	chapters/050-differential/uebungsaufgaben/502.tex		\
	chapters/050-differential/uebungsaufgaben/503.tex		\
	chapters/050-differential/uebungsaufgaben/504.tex		\
	chapters/050-differential/chapter.tex
