#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapterdreieck =							\
	../slides/dreieck/minmax.tex					\
	../slides/dreieck/ordnungsstatistik.tex				\
	../slides/dreieck/test.tex
