#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapterdreieck =							\
	../slides/dreieck/stichprobe.tex				\
	../slides/dreieck/minmax.tex					\
	../slides/dreieck/ordnungsstatistik.tex				\
	../slides/dreieck/orderplot.tex					\
	../slides/dreieck/dichte.tex					\
	../slides/dreieck/beta.tex					\
	../slides/dreieck/betaplot.tex					\
	../slides/dreieck/test.tex
