#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-nav =						\
	papers/nav/packages.tex					\
	papers/nav/main.tex					\
	papers/nav/einleitung.tex				\
	papers/nav/flatearth.tex				\
	papers/nav/geschichte.tex				\
	papers/nav/nautischesdreieck.tex			\
	papers/nav/sincos.tex					\
	papers/nav/trigo.tex					\
	papers/nav/references.bib

