#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-nav =						\
	papers/nav/packages.tex					\
	papers/nav/main.tex					\
	papers/nav/references.bib				\
	papers/nav/teil0.tex					\
	papers/nav/teil1.tex					\
	papers/nav/teil2.tex					\
	papers/nav/teil3.tex

