#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kreismembran =						\
	papers/kreismembran/packages.tex					\
	papers/kreismembran/main.tex					\
	papers/kreismembran/references.bib				\
	papers/kreismembran/teil0.tex					\
	papers/kreismembran/teil1.tex					\
	papers/kreismembran/teil2.tex					\
	papers/kreismembran/teil3.tex

