#
# Makefile -- build and execute some interesting numerical computation
#             programs
# 
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

xxl:	xxl.c
	gcc -o xxl -W -O2 -lgsl xxl.c
