#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-laguerre =						\
	papers/laguerre/packages.tex					\
	papers/laguerre/main.tex					\
	papers/laguerre/references.bib				\
	papers/laguerre/definition.tex					\
	papers/laguerre/eigenschaften.tex				\
	papers/laguerre/quadratur.tex					


