#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-laguerre =						\
	papers/laguerre/packages.tex					\
	papers/laguerre/main.tex					\
	papers/laguerre/references.bib				\
	papers/laguerre/teil0.tex					\
	papers/laguerre/teil1.tex					\
	papers/laguerre/teil2.tex					\
	papers/laguerre/teil3.tex

