#
# Makefile -- make file for the paper laguerre
#
# (c) 2020 Prof Dr Andreas Mueller
#

images: images/laguerre_polynomes.pdf

images/laguerre_polynomes.pdf: scripts/laguerre_plot.py
	python3 scripts/laguerre_plot.py

