#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/080-funktionentheorie/holomorph.tex			\
	chapters/080-funktionentheorie/analytisch.tex			\
	chapters/080-funktionentheorie/cauchy.tex			\
	chapters/080-funktionentheorie/fortsetzung.tex			\
	chapters/080-funktionentheorie/chapter.tex
