#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/080-funktionentheorie/1-holomorph.tex			\
	chapters/080-funktionentheorie/2-analytisch.tex			\
	chapters/080-funktionentheorie/3-cauchy.tex			\
	chapters/080-funktionentheorie/4-fortsetzung.tex		\
	chapters/080-funktionentheorie/5-anwendungen.tex		\
	chapters/080-funktionentheorie/51-gammareflektion.tex		\
	chapters/080-funktionentheorie/52-carlson.tex			\
	chapters/080-funktionentheorie/53-singularitaeten.tex		\
	chapters/080-funktionentheorie/uebungsaufgaben/1.tex		\
	chapters/080-funktionentheorie/uebungsaufgaben/2.tex		\
	chapters/080-funktionentheorie/chapter.tex
