#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/080-funktionentheorie/holomorph.tex			\
	chapters/080-funktionentheorie/analytisch.tex			\
	chapters/080-funktionentheorie/cauchy.tex			\
	chapters/080-funktionentheorie/fortsetzung.tex			\
	chapters/080-funktionentheorie/anwendungen.tex			\
	chapters/080-funktionentheorie/gammareflektion.tex		\
	chapters/080-funktionentheorie/carlson.tex			\
	chapters/080-funktionentheorie/singularitaeten.tex		\
	chapters/080-funktionentheorie/uebungsaufgaben/1.tex		\
	chapters/080-funktionentheorie/uebungsaufgaben/2.tex		\
	chapters/080-funktionentheorie/chapter.tex
