#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-0f1 =						\
	papers/0f1/packages.tex					\
	papers/0f1/main.tex					\
	papers/0f1/references.bib				\
	papers/0f1/teil0.tex					\
	papers/0f1/teil1.tex					\
	papers/0f1/teil2.tex					\
	papers/0f1/teil3.tex

