#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-nlwave =						\
	papers/nlwave/packages.tex					\
	papers/nlwave/main.tex					\
	papers/nlwave/references.bib				\
	papers/nlwave/teil0.tex					\
	papers/nlwave/teil1.tex					\
	papers/nlwave/teil2.tex					\
	papers/nlwave/teil3.tex

