#
# Makefile.inc -- additional dependencies
#
# (c) 2019 Prof Dr Andreas Müller, Hochschule Rapperswil
#
include ../slides/0/Makefile.inc
include ../slides/0f1/Makefile.inc
include ../slides/dreieck/Makefile.inc
include ../slides/ellfilter/Makefile.inc
include ../slides/fm/Makefile.inc
include ../slides/fresnel/Makefile.inc
include ../slides/hermite/Makefile.inc
include ../slides/kra/Makefile.inc
include ../slides/kreismembran/Makefile.inc
include ../slides/kugel/Makefile.inc
include ../slides/laguerre/Makefile.inc
include ../slides/lambertw/Makefile.inc
include ../slides/nav/Makefile.inc
include ../slides/parzyl/Makefile.inc
include ../slides/sturmliouville/Makefile.inc
include ../slides/transfer/Makefile.inc
include ../slides/zeta/Makefile.inc

slides =								\
	$(chapter0)							\
	$(chapter0f1)							\
	$(chapterdreieck)						\
	$(chapterellfilter)						\
	$(chapterfm)							\
	$(chapterfresnel)						\
	$(chapterhermite)						\
	$(chapterkra)							\
	$(chapterkreismembran)						\
	$(chapterkugel)							\
	$(chapterlaguerre)						\
	$(chapterlambertw)						\
	$(chapternav)							\
	$(chapterparzyl)						\
	$(chaptersturmliouville)					\
	$(chaptertransfer)						\
	$(chapterzeta)	



