#
# Makefile to build images
#
all:	primzahlfunktion2.pdf zetaplot.pdf

primzahlfunktion2.pdf:	primzahlfunktion2.tex
	pdflatex primzahlfunktion2.tex

zetaplot.pdf:	zetaplot.tex zetapath.tex 
	pdflatex zetaplot.tex
