#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ellfilter =                        \
    papers/ellfilter/packages.tex               \
    papers/ellfilter/main.tex                   \
    papers/ellfilter/references.bib             \
    papers/ellfilter/einleitung.tex             \
    papers/ellfilter/tschebyscheff.tex          \
    papers/ellfilter/jacobi.tex                 \
    papers/ellfilter/elliptic.tex
