#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-ellfilter =						\
	papers/ellfilter/packages.tex					\
	papers/ellfilter/main.tex					\
	papers/ellfilter/references.bib				\
	papers/ellfilter/teil0.tex					\
	papers/ellfilter/teil1.tex					\
	papers/ellfilter/teil2.tex					\
	papers/ellfilter/teil3.tex

