#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/030-geometrie/1-trigonometrisch.tex			\
	chapters/030-geometrie/2-hyperbolisch.tex			\
	chapters/030-geometrie/3-laenge.tex				\
	chapters/030-geometrie/4-flaeche.tex				\
	chapters/030-geometrie/uebungsaufgaben/1.tex			\
	chapters/030-geometrie/uebungsaufgaben/2.tex			\
	chapters/030-geometrie/chapter.tex
