#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/030-geometrie/trigonometrisch.tex			\
	chapters/030-geometrie/sphaerisch.tex				\
	chapters/030-geometrie/hyperbolisch.tex				\
	chapters/030-geometrie/flaeche.tex				\
	chapters/030-geometrie/laenge.tex				\
	chapters/030-geometrie/uebungsaufgaben/1.tex			\
	chapters/030-geometrie/chapter.tex
