#
# Makefile
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

all:	xexpx.pdf w.pdf buergiausschnitt.pdf

xexpx.pdf:	xexpx.tex
	pdflatex xexpx.tex

w.pdf:	w.tex
	pdflatex w.tex

buergiausschnitt.pdf:	buergiausschnitt.tex buergi1.pdf
	pdflatex buergiausschnitt.tex
