#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kugel =						\
	papers/kugel/packages.tex					\
	papers/kugel/main.tex					\
	papers/kugel/references.bib				\
	papers/kugel/teil0.tex					\
	papers/kugel/teil1.tex					\
	papers/kugel/teil2.tex					\
	papers/kugel/teil3.tex

