#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kugel =						\
	papers/kugel/packages.tex				\
	papers/kugel/main.tex					\
	papers/kugel/references.bib

