#
# Makefile -- nav
#
# (c) 2017 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	nav-handout.pdf MathSem-05-nav.pdf

include ../slides/Makefile.inc

SOURCES = common.tex slides.tex $(slides)

MathSem-05-nav.pdf:	MathSem-05-nav.tex $(SOURCES)
	pdflatex MathSem-05-nav.tex

nav-handout.pdf:	nav-handout.tex $(SOURCES)
	pdflatex nav-handout.tex

thumbnail:	thumbnail.jpg # fix1.jpg

thumbnail.pdf:	MathSem-05-nav.pdf
	pdfjam --outfile thumbnail.pdf --papersize '{16cm,9cm}' \
		MathSem-05-nav.pdf 1
thumbnail.jpg:	thumbnail.pdf
	convert -density 300 thumbnail.pdf \
                -resize 1920x1080 -units PixelsPerInch thumbnail.jpg

fix1.pdf:	MathSem-05-nav.pdf
	pdfjam --outfile fix1.pdf --papersize '{16cm,9cm}' \
		MathSem-05-nav.pdf 1
fix1.jpg:	fix1.pdf
	convert -density 300 fix1.pdf \
                -resize 1920x1080 -units PixelsPerInch fix1.jpg

