#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/020-exponential/zins.tex				\
	chapters/020-exponential/log.tex				\
	chapters/020-exponential/lambertw.tex				\
	chapters/020-exponential/uebungsaufgaben/0.tex			\
	chapters/020-exponential/chapter.tex
