#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/020-exponential/1-zins.tex				\
	chapters/020-exponential/2-log.tex				\
	chapters/020-exponential/3-lambertw.tex				\
	chapters/020-exponential/dilog.tex				\
	chapters/020-exponential/eili.tex				\
	chapters/020-exponential/uebungsaufgaben/200.tex		\
	chapters/020-exponential/uebungsaufgaben/201.tex		\
	chapters/020-exponential/uebungsaufgaben/202.tex		\
	chapters/020-exponential/chapter.tex
