#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/070-orthogonalitaet/1-orthogonal.tex			\
	chapters/070-orthogonalitaet/2-rekursion.tex			\
	chapters/070-orthogonalitaet/3-rodrigues.tex			\
	chapters/070-orthogonalitaet/4-legendredgl.tex			\
	chapters/070-orthogonalitaet/5-bessel.tex			\
	chapters/070-orthogonalitaet/6-sturm.tex			\
	chapters/070-orthogonalitaet/7-gaussquadratur.tex		\
	chapters/070-orthogonalitaet/uebungsaufgaben/701.tex		\
	chapters/070-orthogonalitaet/chapter.tex
