#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/070-orthogonalitaet/orthogonal.tex			\
	chapters/070-orthogonalitaet/rekursion.tex			\
	chapters/070-orthogonalitaet/rodrigues.tex			\
	chapters/070-orthogonalitaet/legendredgl.tex			\
	chapters/070-orthogonalitaet/bessel.tex				\
	chapters/070-orthogonalitaet/jacobi.tex				\
	chapters/070-orthogonalitaet/sturm.tex				\
	chapters/070-orthogonalitaet/gaussquadratur.tex			\
	chapters/070-orthogonalitaet/chapter.tex
