#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/040-rekursion/gamma.tex				\
	chapters/040-rekursion/bohrmollerup.tex				\
	chapters/040-rekursion/integral.tex				\
	chapters/040-rekursion/beta.tex					\
	chapters/040-rekursion/betaverteilung.tex			\
	chapters/040-rekursion/linear.tex				\
	chapters/040-rekursion/hypergeometrisch.tex			\
	chapters/040-rekursion/uebungsaufgaben/401.tex			\
	chapters/040-rekursion/uebungsaufgaben/402.tex			\
	chapters/040-rekursion/uebungsaufgaben/403.tex			\
	chapters/040-rekursion/uebungsaufgaben/404.tex			\
	chapters/040-rekursion/uebungsaufgaben/405.tex			\
	chapters/040-rekursion/chapter.tex
