#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/040-rekursion/gamma.tex				\
	chapters/040-rekursion/chapter.tex
