#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/040-rekursion/1-gamma.tex				\
	chapters/040-rekursion/11-bohrmollerup.tex			\
	chapters/040-rekursion/12-integral.tex				\
	chapters/040-rekursion/2-beta.tex				\
	chapters/040-rekursion/21-betaverteilung.tex			\
	chapters/040-rekursion/3-linear.tex				\
	chapters/040-rekursion/4-hypergeometrisch.tex			\
	chapters/040-rekursion/uebungsaufgaben/401.tex			\
	chapters/040-rekursion/uebungsaufgaben/402.tex			\
	chapters/040-rekursion/uebungsaufgaben/403.tex			\
	chapters/040-rekursion/uebungsaufgaben/404.tex			\
	chapters/040-rekursion/uebungsaufgaben/405.tex			\
	chapters/040-rekursion/chapter.tex
