#
# Makefile -- build images
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
all:	nonanalytic.pdf integralanalytisch.pdf laurent.pdf \
	fortsetzreziprok.pdf forts.pdf logforts.pdf

nonanalytic.pdf:	nonanalytic.tex
	pdflatex nonanalytic.tex

integralanalytisch.pdf:	integralanalytisch.tex
	pdflatex integralanalytisch.tex

laurent.pdf:	laurent.tex
	pdflatex laurent.tex

fortsetzreziprok.pdf:	fortsetzreziprok.tex
	pdflatex fortsetzreziprok.tex

forts.pdf:	forts.tex
	pdflatex forts.tex

logforts.pdf:	logforts.tex
	pdflatex logforts.tex

