#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapterfresnel =							\
	../slides/fresnel/integrale.tex					\
	../slides/fresnel/kruemmung.tex					\
	../slides/fresnel/klothoide.tex					\
	../slides/fresnel/numerik.tex					\
	../slides/fresnel/apfel.tex
