#
# Makefile for images
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

all:	hyperbelflaeche.pdf polargleichung.pdf

hyperbelflaeche.pdf:	hyperbelflaeche.tex
	pdflatex hyperbelflaeche.tex

polargleichung.pdf:	polargleichung.tex
	pdflatex polargleichung.tex

