#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kra =						\
	papers/kra/packages.tex				\
	papers/kra/main.tex					\
	papers/kra/references.bib			\
	papers/kra/einleitung.tex			\
	papers/kra/loesung.tex				\
	papers/kra/anwendung.tex			\

