#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kra =						\
	papers/kra/packages.tex					\
	papers/kra/main.tex					\
	papers/kra/references.bib				\
	papers/kra/teil0.tex					\
	papers/kra/teil1.tex					\
	papers/kra/teil2.tex					\
	papers/kra/teil3.tex

