#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fresnel =						\
	papers/fresnel/packages.tex					\
	papers/fresnel/main.tex					\
	papers/fresnel/references.bib				\
	papers/fresnel/teil0.tex					\
	papers/fresnel/teil1.tex					\
	papers/fresnel/teil2.tex					\
	papers/fresnel/teil3.tex

