#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-parzyl =						\
	papers/parzyl/packages.tex					\
	papers/parzyl/main.tex					\
	papers/parzyl/references.bib				\
	papers/parzyl/teil0.tex					\
	papers/parzyl/teil1.tex					\
	papers/parzyl/teil2.tex					\
	papers/parzyl/teil3.tex

