#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES = $(CHAPTERFILES)						\
	chapters/090-pde/gleichung.tex					\
	chapters/090-pde/separation.tex					\
	chapters/090-pde/rechteck.tex					\
	chapters/090-pde/kreis.tex					\
	chapters/090-pde/kugel.tex					\
	chapters/090-pde/uebungsaufgaben/901.tex			\
	chapters/090-pde/chapter.tex
