#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2022 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#

CHAPTERFILES += 							\
	chapters/090-pde/1-gleichung.tex				\
	chapters/090-pde/2-separation.tex				\
	chapters/090-pde/3-rechteck.tex					\
	chapters/090-pde/4-geometrie.tex				\
	chapters/090-pde/uebungsaufgaben/901.tex			\
	chapters/090-pde/chapter.tex
