#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter0 =								\
	../slides/0/frueher.tex						\
	../slides/0/funktionen.tex					\
	../slides/0/fehler.tex						\
	../slides/0/info.tex						\
	../slides/0/intro.tex						\
	../slides/0/wassindss.tex					\
	../slides/0/was.tex						\
	../slides/0/intro.tex						\
	../slides/0/nextsteps.tex					\
	../slides/0/was.tex						\
	../slides/0/latextipps.tex					\
	../slides/0/themen1.tex						\
	../slides/0/themen2.tex						\
	../slides/0/themen3.tex
