#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter0 =								\
	../slides/0/frueher.tex						\
	../slides/0/funktionen.tex					\
	../slides/0/info.tex						\
	../slides/0/intro.tex						\
	../slides/0/was.tex
