#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-sturmliouville =						\
	papers/sturmliouville/packages.tex					\
	papers/sturmliouville/main.tex					\
	papers/sturmliouville/references.bib				\
	papers/sturmliouville/teil0.tex					\
	papers/sturmliouville/teil1.tex					\
	papers/sturmliouville/teil2.tex					\
	papers/sturmliouville/teil3.tex

