#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-sturmliouville =							\
	papers/sturmliouville/packages.tex					\
	papers/sturmliouville/main.tex						\
	papers/sturmliouville/references.bib				\
	papers/sturmliouville/einleitung.tex				\
	papers/sturmliouville/eigenschaften.tex				\
	papers/sturmliouville/waermeleitung_beispiel.tex	\
	papers/sturmliouville/tschebyscheff_beispiel.tex
