#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-hermite =						\
	papers/hermite/packages.tex					\
	papers/hermite/main.tex					\
	papers/hermite/references.bib				\
	papers/hermite/teil0.tex					\
	papers/hermite/teil1.tex					\
	papers/hermite/teil2.tex					\
	papers/hermite/teil3.tex

