#
# Makefile -- build speziellefunktionen.tex poster
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
speziellefunktionen.pdf:	speziellefunktionen.tex ../cover/buchcover.png
	pdflatex speziellefunktionen.tex
