#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-dreieck =						\
	papers/dreieck/packages.tex					\
	papers/dreieck/main.tex					\
	papers/dreieck/references.bib				\
	papers/dreieck/teil0.tex					\
	papers/dreieck/teil1.tex					\
	papers/dreieck/teil2.tex					\
	papers/dreieck/teil3.tex

