include papers/000template/Makefile.inc
include papers/lambertw/Makefile.inc
include papers/fm/Makefile.inc
include papers/parzyl/Makefile.inc
include papers/fresnel/Makefile.inc
include papers/kreismembran/Makefile.inc
include papers/sturmliouville/Makefile.inc
include papers/laguerre/Makefile.inc
include papers/zeta/Makefile.inc
include papers/0f1/Makefile.inc
include papers/nav/Makefile.inc
include papers/transfer/Makefile.inc
include papers/kra/Makefile.inc
include papers/kugel/Makefile.inc
include papers/hermite/Makefile.inc
include papers/ellfilter/Makefile.inc
include papers/dreieck/Makefile.inc

TEXFILES = \
	$(dependencies-000template) \
	$(dependencies-lambertw) \
	$(dependencies-fm) \
	$(dependencies-parzyl) \
	$(dependencies-fresnel) \
	$(dependencies-kreismembran) \
	$(dependencies-sturmliouville) \
	$(dependencies-laguerre) \
	$(dependencies-zeta) \
	$(dependencies-0f1) \
	$(dependencies-nav) \
	$(dependencies-transfer) \
	$(dependencies-kra) \
	$(dependencies-kugel) \
	$(dependencies-hermite) \
	$(dependencies-ellfilter) \
	$(dependencies-dreieck) \

