#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-transfer =						\
	papers/transfer/packages.tex					\
	papers/transfer/main.tex					\
	papers/transfer/references.bib				\
	papers/transfer/teil0.tex					\
	papers/transfer/teil1.tex					\
	papers/transfer/teil2.tex					\
	papers/transfer/teil3.tex

