#
# Makefile.inc 
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapterhermite =							\
	../slides/hermite/normalintegrale.tex				\
	../slides/hermite/normalhermite.tex				\
	../slides/hermite/hermiteentwicklung.tex			\
	../slides/hermite/loesung.tex					\
	../slides/hermite/skalarprodukt.tex				\
	../slides/hermite/test.tex
